--- 
- name: update package
  apt:
    update_cache: yes


   
- name: Download tomcat 
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.42/bin/apache-tomcat-7.0.42.tar.gz
    dest: /home/narasimha/apache-tomcat-7.0.42.tar.gz
    force_basic_auth: yes

   
- name: Create a directory 
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'
 
 
- name: i want to extract tar file
  unarchive:
      src: /home/narasimha/apache-tomcat-7.0.42.tar.gz
      dest: /opt/tomcat/
      extra_opts: [--strip-components=1]
      remote_src: yes 