--- 
 - name: Create a directory 
   file:
    path: /opt/tomcat
    state: directory
    mode: '0755'
 

 - name: Recursively tomcat group 
   file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

 - name: tomcat group read access 
   file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+r
    recurse: yes
    owner: tomcat
    group: tomcat

 - name: tomcat group read access 
   file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+x
    owner: tomcat
    group: tomcat

 - name: tomcat user the owner of the webapps
   file:
    path: /opt/tomcat/webapps/
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

 - name: tomcat user the owner of the work  
   file:
    path: /opt/tomcat/work/
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

 - name: tomcat user the owner of the temp  
   file:
    path: /opt/tomcat/temp/
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

 - name: tomcat user the owner of the logs  
   file:
    path: /opt/tomcat/logs/
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

   
  